name: Deploy API Desafio AMA Gestão

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            